package collection;

import annotations.AutoGenerated;
import annotations.GreaterThan;
import annotations.NotNull;
import annotations.Unique;

import java.io.Serializable;

/**
 * class for future implementation
 * (literally anything that can have id)
 */
public class IdHolder implements Serializable {
    @NotNull
    @GreaterThan(0)
    @AutoGenerated
    @Unique
    private Integer id;//Поле не может быть null, Значение поля должно быть больше 0, Значение этого поля должно быть уникальным, Значение этого поля должно генерироваться автоматически

    public IdHolder(int id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(int id){
        this.id = id;
    }
}
